### ISSUE TITLE
refactor(http): route names aren't consistent

### ISSUE THREAD

**Issue by williamtdr** [csci4950tgt/api#25]
- Look at new ways to use the REST conventions to make the endpoints more intuitive.
- This will break frontend, probably

**Comment by rafibarash** [comment]
Basing off [this article](https://restfulapi.net/resource-naming/) on REST API naming conventions, I think we should rename the API as the following:

- GET /api/honeyclients (**get all honeyclients, or maybe first 50 or something**)
- POST /api/honeyclients (**creates a honeyclient**)
- GET /api/honeyclients/{id} (**get all information associated with a specific honeyclient**)
- GET /api/honeyclients/{id}/artifacts **get all file artifacts like screenshots or js associated with specific honeyclient**)
- GET /api/honeyclients/{id}/artifacts/{artifact-name} (**get specific artifact associated with a honeyclient**)
