### ISSUE TITLE
Add Github Action Workflow for automated testing on merges to master

### ISSUE THREAD

**Issue by rafibarash** [csci4950tgt/api#38]
Should follow [this article](https://help.github.com/en/github/automating-your-workflow-with-github-actions/configuring-a-workflow) to create an action, using [this syntax](https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions). Shouldn't be very difficult

**Comment by jin-yng** [comment]
Fix creds
